server:
  port: 8080
  servlet:
    context-path:
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url:
    username: root
    password: 712459
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
  session:
    store-type: redis
  redis:
    host: localhost
    password:
    port: 6379